'This script has been generated by PowerPCB's VB Script Wizard on 2018/3/14 10:18:35
'It will create reports in Microsoft Excel Format.
'You can use the following code as a skeleton for your own VB scripts

'Array of column names. You can modify it to rename columns
Const Columns = Array("Name", "Part Type", "Value", "PCB Decal")
Dim fname As String

Sub Main
	fname = ActiveDocument
	If fname = "" Then
		fname = "Untitled"
	End If
	tempFile = DefaultFilePath & "\temp.txt"
	Open tempFile For Output As #1

	StatusBarText = "Generating report..."
	'Output table header
	For i = 0 to UBound(Columns)
		OutCell Columns(i)
	Next
	Print #1
	'Output table rows
	For Each part in ActiveDocument.Components
		OutCell part.Name
		OutCell part.PartType
		OutCell AttrVal(part, "Value")
		OutCell part.Decal
		Print #1
	Next part

	StatusBarText = ""
	Close #1
	ExportToExcel
End Sub

Function AttrVal (obj As Object, nm As String)
	AttrVal = IIf(obj.Attributes(nm) Is Nothing, "", obj.Attributes(nm))
End Function

Sub ExportToExcel
	FillClipboard
	Dim xl As Object
	On Error Resume Next
	Set xl =  GetObject(,"Excel.Application")
	On Error GoTo ExcelError	' Enable error trapping.
	If xl Is Nothing Then
		Set xl =  CreateObject("Excel.Application")
	End If
	xl.Visible = True
	xl.Workbooks.Add
	xl.ActiveSheet.Paste
	xl.Range("A1:D1").Font.Bold = True
	xl.Range("A1:D1").NumberFormat = "@"
	xl.Range("A1:D1").AutoFilter
	xl.ActiveSheet.UsedRange.Columns.AutoFit
	'Output Report Header
	xl.Rows(1).Insert
	xl.Rows(1).Cells(1) = Space(1) & "Part Report5 for " & fname & " on " & Now
	xl.Rows(2).Insert
	xl.Rows(1).Font.bold = True
	'Output Design Totals
	lastRow = xl.ActiveSheet.UsedRange.Rows.Count + 1
	xl.Rows(lastRow + 1).Font.bold = True
	xl.Rows(lastRow + 1).Cells(1) = Space(1) & "Design Part count: " & ActiveDocument.Components.Count
	xl.Range("A1").Select
	On Error GoTo 0 ' Disable error trapping. 
	Exit Sub    

ExcelError:
	MsgBox Err.Description, vbExclamation, "Error Running Excel"
	On Error GoTo 0 ' Disable error trapping.    
	Exit Sub
End Sub

Sub OutCell (txt As String)
	Print #1, txt; vbTab;
End Sub

Sub FillClipboard
	StatusBarText = "Export Data To Clipboard..."
	' Load whole file to string variable    
	tempFile = DefaultFilePath & "\temp.txt"
	Open tempFile  For Input As #1
	L = LOF(1)
	AllData$ = Input$(L,1)
	Close #1
	'Copy whole data to clipboard
	Clipboard AllData$ 
	Kill tempFile
	StatusBarText = ""
End Sub
