#include "key.h"
void KEY_Init()
{
 GPIO_Init(KEY_UP_PORT,KEY_UP_PIN, GPIO_Mode_In_FL_IT);
 GPIO_Init(KEY_DOWN_PORT,KEY_DOWN_PIN, GPIO_Mode_In_FL_IT);
 GPIO_Init(KEY_EAST_PORT,KEY_EAST_PIN, GPIO_Mode_In_FL_IT);
 GPIO_Init(KEY_WEST_PORT,KEY_WEST_PIN, GPIO_Mode_In_FL_IT); 
 GPIO_Init(KEY_SOUTH_PORT,KEY_SOUTH_PIN, GPIO_Mode_In_FL_IT);
 GPIO_Init(KEY_START_PORT,KEY_NORTH_PIN, GPIO_Mode_In_FL_IT); 
 GPIO_Init(KEY_NORTH_PORT,KEY_START_PIN, GPIO_Mode_In_FL_IT);
 GPIO_Init(KEY_STOP_PORT,KEY_STOP_PIN, GPIO_Mode_In_FL_IT); 
 GPIO_Init(KEY_BREAK_PORT,KEY_BREAK_PIN, GPIO_Mode_In_FL_IT);
}


