#include "stm8s.h"
#include "bsp.h"

void CLK_INIT()
{
  CLK_HSIPrescalerConfig(CLK_PRESCALER_HSIDIV1);
}
void GPIO_INIT()
{
  
  /* Initialize I/Os in Output Mode */
  GPIO_Init(TM1629A_DIO_PORT, TM1629A_DIO, GPIO_MODE_OUT_OD_LOW_FAST);
  GPIO_Init(TM1629A_CLK_STB_PORT, TM1629A_CLK, GPIO_MODE_OUT_PP_LOW_FAST);   
  GPIO_Init(TM1629A_CLK_STB_PORT, STB, GPIO_MODE_OUT_PP_LOW_FAST);  
  
  /*iic driver*/
  GPIO_Init(MCU_IIC_PORT, MCU_SDA, GPIO_MODE_OUT_OD_LOW_FAST);
  GPIO_Init(MCU_IIC_PORT, MCU_SCL, GPIO_MODE_OUT_PP_LOW_FAST);   
  
  /*iic driver*/
  GPIO_Init(SENSOR_IIC_SDA_PORT, SENSOR_SDA, GPIO_MODE_OUT_OD_LOW_FAST);
  GPIO_Init(SENSOR_IIC_SCK_PORT, SENSOR_SCL, GPIO_MODE_OUT_PP_LOW_FAST); 
  
  
  
  /*buzzer driver*/
  GPIO_Init(BUZZER_PORT, BUZZER, GPIO_MODE_OUT_PP_LOW_FAST); 
  
  GPIO_Init(PWM_PORT, PWM_10KHZ, GPIO_MODE_OUT_PP_LOW_FAST); 
  GPIO_Init(PWM_PORT, PWM_10KHZ1, GPIO_MODE_OUT_PP_LOW_FAST); 
  GPIO_Init(PWM_PORT, PWM_50HZ, GPIO_MODE_OUT_PP_LOW_FAST); 
  GPIO_Init(K37_PORT, K3, GPIO_MODE_OUT_PP_LOW_FAST);   
  GPIO_Init(K37_PORT, K7, GPIO_MODE_OUT_PP_LOW_FAST); 
  GPIO_Init(K6_PORT, K6, GPIO_MODE_OUT_PP_LOW_FAST); 
  GPIO_Init(K4_PORT, K4, GPIO_MODE_OUT_PP_LOW_FAST); 
  
  
  
  /* SPI configuration */
  SPI_DeInit();
  GPIO_Init(RF_PORT, MCU_SCK, GPIO_MODE_OUT_PP_HIGH_FAST);
  GPIO_Init(RF_PORT, MCU_MOSI, GPIO_MODE_IN_FL_NO_IT);
  GPIO_Init(RF_PORT, MCU_CS, GPIO_MODE_OUT_PP_HIGH_FAST);
  GPIO_Init(RF_PORT, MCU_MISO, GPIO_MODE_OUT_PP_HIGH_FAST);
  GPIO_Init(RF_PORT, MCU_PDN, GPIO_MODE_OUT_PP_HIGH_FAST);
  GPIO_Init(RF_PORT, MCU_IRQ, GPIO_MODE_IN_FL_IT);
  
  EXTI_SetExtIntSensitivity(EXTI_PORT_GPIOC, EXTI_SENSITIVITY_FALL_ONLY);
  EXTI_SetTLISensitivity(EXTI_TLISENSITIVITY_FALL_ONLY);
  GPIO_Init(MCU_RF_GPIO0_PORT, MCU_RF_GPIO0, GPIO_MODE_IN_FL_IT);
  
  EXTI_SetExtIntSensitivity(EXTI_PORT_GPIOD, EXTI_SENSITIVITY_FALL_ONLY);
  EXTI_SetTLISensitivity(EXTI_TLISENSITIVITY_FALL_ONLY);
  
  /* Initialize SPI in Slave mode  */
  SPI_Init(SPI_FIRSTBIT_LSB, SPI_BAUDRATEPRESCALER_2, SPI_MODE_SLAVE, SPI_CLOCKPOLARITY_LOW,
           SPI_CLOCKPHASE_1EDGE, SPI_DATADIRECTION_2LINES_FULLDUPLEX, SPI_NSS_SOFT,(uint8_t)0x07);
  /* Enable the SPI*/
  SPI_Cmd(ENABLE);
  
  
  GPIO_Init(IRED_PORT, IRED, GPIO_MODE_IN_FL_NO_IT); 
  GPIO_Init(IN_PORT, IN, GPIO_MODE_IN_FL_NO_IT); 
  GPIO_Init(FEED_PORT, FEED, GPIO_MODE_IN_FL_NO_IT); 
  
  
  
  
}

void ADC_Config()
{
  /*  Init GPIO for ADC1 */
  GPIO_Init(ADC_PORT, AD, GPIO_MODE_IN_FL_NO_IT);
  
  /* De-Init ADC peripheral*/
  ADC1_DeInit();
  
  /* Init ADC1 peripheral */
  ADC1_Init(ADC1_CONVERSIONMODE_CONTINUOUS, ADC1_CHANNEL_0, ADC1_PRESSEL_FCPU_D2, \
  ADC1_EXTTRIG_TIM, DISABLE, ADC1_ALIGN_RIGHT, ADC1_SCHMITTTRIG_CHANNEL0,\
      DISABLE);
  
  /* Enable EOC interrupt */
  ADC1_ITConfig(ADC1_IT_EOC,ENABLE);
  
  /* Enable general interrupts */  
  enableInterrupts();
  
  /*Start Conversion */
  ADC1_StartConversion();
}

